name: Docs
on: [push]
jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/" 
          pre-build-command: "pip install sphinx-rtd-theme"
          build-command: "sphinx-build -b html . _build"


